# BÀI TẬP: TITANIC
**Nguồn:** kaggle.com/c/titanic (891 dòng)

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')

csv_path = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [2]:
# TODO
print("Kích thước dữ liệu:", df.shape)

Kích thước dữ liệu: (891, 15)

In [3]:
print("Tên các cột: ", ", ".join(df.columns))

Tên các cột:  survived, pclass, sex, age, sibsp, parch, fare, embarked, class, who, adult_male, deck, embark_town, alive, alone

In [5]:
print(df.dtypes)

survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object

## A.2. Missing values & Duplicate data

In [7]:
# TODO
print("Số lượng các giá trị bị thiếu: ", df.isnull().sum().sum())

Số lượng các giá trị bị thiếu:  869

In [9]:
print(df.duplicated().sum())

107

## A.3. Invalid values

In [11]:
# TODO
print("age:", ((df['age'] < 0) | (df['age'] > 100)).sum())
print("fare:", (df['fare'] < 0).sum())
print("sibsp:", (df['sibsp'] < 0).sum())
print("parch:", (df['parch'] < 0).sum())

print("survived:", (~df['survived'].isin([0, 1])).sum())
print("pclass:", (~df['pclass'].isin([1, 2, 3])).sum())
print("sex:", (~df['sex'].isin(['male', 'female'])).sum())
print("alone:", (~df['alone'].isin(['True', 'False'])).sum())
print("alive:", (~df['alive'].isin(['yes', 'no'])).sum())

age: 0
fare: 0
sibsp: 0
parch: 0
survived: 0
pclass: 0
sex: 0
alone: 891
alive: 0

## A.4. Create a new column
Tạo cột `family_size` = sibsp + parch + 1.

In [13]:
# TODO
df['family_size'] = df['sibsp'] + df['parch'] + 1
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,2
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,2
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [14]:
# TODO
df[['age', 'fare', 'sibsp', 'parch']].mean

<bound method DataFrame.mean of       age     fare  sibsp  parch
0    22.0   7.2500      1      0
1    38.0  71.2833      1      0
2    26.0   7.9250      0      0
3    35.0  53.1000      1      0
4    35.0   8.0500      0      0
..    ...      ...    ...    ...
886  27.0  13.0000      0      0
887  19.0  30.0000      0      0
888   NaN  23.4500      1      2
889  26.0  30.0000      0      0
890  32.0   7.7500      0      0

[891 rows x 4 columns]>

In [18]:
df[['age', 'fare', 'sibsp', 'parch']].median

<bound method DataFrame.median of       age     fare  sibsp  parch
0    22.0   7.2500      1      0
1    38.0  71.2833      1      0
2    26.0   7.9250      0      0
3    35.0  53.1000      1      0
4    35.0   8.0500      0      0
..    ...      ...    ...    ...
886  27.0  13.0000      0      0
887  19.0  30.0000      0      0
888   NaN  23.4500      1      2
889  26.0  30.0000      0      0
890  32.0   7.7500      0      0

[891 rows x 4 columns]>

In [15]:
df[['age', 'fare', 'sibsp', 'parch']].mode

<bound method DataFrame.mode of       age     fare  sibsp  parch
0    22.0   7.2500      1      0
1    38.0  71.2833      1      0
2    26.0   7.9250      0      0
3    35.0  53.1000      1      0
4    35.0   8.0500      0      0
..    ...      ...    ...    ...
886  27.0  13.0000      0      0
887  19.0  30.0000      0      0
888   NaN  23.4500      1      2
889  26.0  30.0000      0      0
890  32.0   7.7500      0      0

[891 rows x 4 columns]>

## Group 2 — Dispersion

In [19]:
# TODO
range_values = df[['age', 'fare', 'sibsp', 'parch']].max() - df[['age', 'fare', 'sibsp', 'parch']].min()
print(range_values)

age       79.5800
fare     512.3292
sibsp      8.0000
parch      6.0000
dtype: float64

In [20]:
var_values = df[['age', 'fare', 'sibsp', 'parch']].var()
print(var_values)

age       211.019125
fare     2469.436846
sibsp       1.216043
parch       0.649728
dtype: float64

In [21]:
std_values = df[['age', 'fare', 'sibsp', 'parch']].std()
print(std_values)

age      14.526497
fare     49.693429
sibsp     1.102743
parch     0.806057
dtype: float64

In [22]:
iqr_values = df[['age', 'fare', 'sibsp', 'parch']].quantile(0.75) - df[['age', 'fare', 'sibsp', 'parch']].quantile(0.25)
print(iqr_values)

age      17.8750
fare     23.0896
sibsp     1.0000
parch     0.0000
dtype: float64

## Group 3 — Location and Shape

In [25]:
# TODO
print(df[['age', 'fare', 'sibsp', 'parch']].quantile(0.25))
print("\n", df[['age', 'fare', 'sibsp', 'parch']].quantile(0.50))
print("\n", df[['age', 'fare', 'sibsp', 'parch']].quantile(0.75))

age      20.1250
fare      7.9104
sibsp     0.0000
parch     0.0000
Name: 0.25, dtype: float64

 age      28.0000
fare     14.4542
sibsp     0.0000
parch     0.0000
Name: 0.5, dtype: float64

 age      38.0
fare     31.0
sibsp     1.0
parch     0.0
Name: 0.75, dtype: float64

In [26]:
print(df[['age', 'fare', 'sibsp', 'parch']].skew())
print("\n", df[['age', 'fare', 'sibsp', 'parch']].kurt())

age      0.389108
fare     4.787317
sibsp    3.695352
parch    2.749117
dtype: float64

 age       0.178274
fare     33.398141
sibsp    17.880420
parch     9.778125
dtype: float64

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Hạng vé nào có tỷ lệ sống sót cao nhất, chênh lệch bao nhiêu so với hạng thấp nhất?

In [28]:
# TODO
survival = df.groupby('pclass')['survived'].mean()

print("--- TỶ LỆ SỐNG SÓT THEO HẠNG VÉ ---")
print(survival)

max_class = survival.idxmax()
max_rate = survival.max()

min_class = survival.idxmin()
min_rate = survival.min()

chenh_lech = max_rate - min_rate

print(f"\n- Hạng vé có tỷ lệ sống sót cao nhất: Hạng {max_class} ({max_rate:.2%})")
print(f"- Hạng vé có tỷ lệ sống sót thấp nhất: Hạng {min_class} ({min_rate:.2%})")
print(f"- Mức chênh lệch: {diff:.2%} (hoặc gấp {max_rate/min_rate:.2f} lần)")

--- TỶ LỆ SỐNG SÓT THEO HẠNG VÉ ---
pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

- Hạng vé có tỷ lệ sống sót cao nhất: Hạng 1 (62.96%)
- Hạng vé có tỷ lệ sống sót thấp nhất: Hạng 3 (24.24%)
- Mức chênh lệch: 38.73% (hoặc gấp 2.60 lần)

## Câu hỏi 2: Giới tính hay hạng vé ảnh hưởng đến sống sót mạnh hơn?

In [33]:
# TODO
sex_survival = df.groupby('sex')['survived'].mean()
sex_diff = sex_survival['female'] - sex_survival['male']

class_survival = df.groupby('pclass')['survived'].mean()
class_diff = class_survival[1] - class_survival[3]

print(f"Tỷ lệ sống theo Giới tính:\n{sex_survival}\nChênh lệch Nam - Nữ: {sex_diff:.2%}\n")
print(f"Tỷ lệ sống theo Hạng vé:\n{class_survival}\nChênh lệch Hạng 1 - Hạng 3: {class_diff:.2%}\n")

pivot = df.pivot_table(index='sex', columns='pclass', values='survived', aggfunc='mean')
print("TỶ LỆ SỐNG SÓT KẾT HỢP (GENDER x PCLASS)")
print(pivot)

Tỷ lệ sống theo Giới tính:
sex
female    0.742038
male      0.188908
Name: survived, dtype: float64
Chênh lệch Nam - Nữ: 55.31%

Tỷ lệ sống theo Hạng vé:
pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64
Chênh lệch Hạng 1 - Hạng 3: 38.73%

TỶ LỆ SỐNG SÓT KẾT HỢP (GENDER x PCLASS)
pclass         1         2         3
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

## Câu hỏi 3: Vé đắt hơn có thực sự sống sót cao hơn không?

In [30]:
# TODO
fare_stats = df.groupby('survived')['fare'].agg(['mean', 'median', 'std'])
print("GIÁ VÉ TRUNG BÌNH THEO TRẠNG THÁI SỐNG SÓT")
print(fare_stats)

df['fare_group'] = pd.qcut(df['fare'], q=4, labels=['Rất rẻ', 'Rẻ', 'Trung bình', 'Đắt'])
print("\nTỈ LỆ SỐNG SÓT THEO NHÓM GIÁ VÉ")
print(df.groupby('fare_group', observed=False)['survived'].mean())

corr, p_value = stats.pointbiserialr(df['survived'], df['fare'])
print(f"\nHệ số tương quan: {corr:.3f} (p-value: {p_value:.3e})")

GIÁ VÉ TRUNG BÌNH THEO TRẠNG THÁI SỐNG SÓT
               mean  median        std
survived
0         22.117887    10.5  31.388207
1         48.395408    26.0  66.596998

TỈ LỆ SỐNG SÓT THEO NHÓM GIÁ VÉ
fare_group
Rất rẻ        0.197309
Rẻ            0.303571
Trung bình    0.454955
Đắt           0.581081
Name: survived, dtype: float64

Hệ số tương quan: 0.257 (p-value: 6.120e-15)

## Câu hỏi 4: Gia đình đông người có ảnh hưởng đến khả năng sống sót không?

In [32]:
# TODO
df['family_size'] = df['sibsp'] + df['parch'] + 1

def categorize_family(size):
    if size == 1:
        return 'Đi một mình (1)'
    elif 2 <= size <= 4:
        return 'Gia đình nhỏ (2-4)'
    else:
        return 'Gia đình đông (>4)'

df['family_type'] = df['family_size'].apply(categorize_family)

print("TỶ LỆ SỐNG SÓT THEO SỐ THÀNH VIÊN")
print(df.groupby('family_size')['survived'].agg(['count', 'mean']))

print("\nTỶ LỆ SỐNG SÓT THEO NHÓM GIA ĐÌNH")
print(df.groupby('family_type')['survived'].agg(['count', 'mean']))

TỶ LỆ SỐNG SÓT THEO SỐ THÀNH VIÊN
             count      mean
family_size
1              537  0.303538
2              161  0.552795
3              102  0.578431
4               29  0.724138
5               15  0.200000
6               22  0.136364
7               12  0.333333
8                6  0.000000
11               7  0.000000

TỶ LỆ SỐNG SÓT THEO NHÓM GIA ĐÌNH
                    count      mean
family_type
Gia đình nhỏ (2-4)    292  0.578767
Gia đình đông (>4)     62  0.161290
Đi một mình (1)       537  0.303538

## Câu hỏi 5: Cảng lên tàu (embark_town) nào có tỷ lệ sống sót cao nhất?

In [34]:
# TODO
embark_survival = df.groupby('embark_town')['survived'].agg(
    So_luong='count',
    Ty_le_song='mean'
)

print("TỶ LỆ SỐNG SÓT THEO CẢNG LÊN TÀU")
print(embark_survival)

TỶ LỆ SỐNG SÓT THEO CẢNG LÊN TÀU
             So_luong  Ty_le_song
embark_town
Cherbourg         168    0.553571
Queenstown         77    0.389610
Southampton       644    0.336957

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể về dữ liệu Titanic.

*(Viết insight của bạn vào đây...)*